### ISSUE TITLE
[BUG] "sv stop sshd" does not kill sshd process

### ISSUE THREAD

**Issue by adoyle-h** [termux/termux-services#18]
## problem reproduction

```sh
$ ps -ef  | grep sshd
u0_a565   2396  2395  0  1970 ?        00:00:04 runsv sshd
u0_a565  11266  2396  0  1970 ?        00:00:00 sshd -D -f /data/data/com.termux/files/home/etc/ssh/sshd_config -e
u0_a565  11294 11266  0  1970 ?        00:00:00 /data/data/com.termux/files/usr/bin/sshd -D -f /data/data/com.termux/files/home/etc/ssh/sshd_config -e -R

$ cat service/sshd/supervise/pid
11266

# log pid is empty
$ cat cat service/sshd/log/supervise/pid

$ sv stop sshd
ok: down: sshd: 1s

# `sv stop sshd` only kill pid 11266. The pid 11294 is still running.
$ ps -ef  | grep sshd
u0_a565   2396  2395  0  1970 ?        00:00:04 runsv sshd
u0_a565  11294     1  0  1970 ?        00:00:00 /data/data/com.termux/files/usr/bin/sshd -D -f /data/data/com.termux/files/home/etc/ssh/sshd_config -e -R
```

## What I expected

Kill both pid 11266 and 11294.

## sshd service config

```
$ cat service/sshd/run
#!/data/data/com.termux/files/usr/bin/sh
exec sshd -D -f /data/data/com.termux/files/home/etc/ssh/sshd_config -e 2>&1

# down script is empty
$ cat service/sshd/down
```

**Comment by Grimler91** [comment]
11294 isn't killed since it isn't supervised by run it, and apparently it continues running fine if parent is killed. 
We could maybe add a special finish script to kill children as well.

How do you spawn the second instance? By opening a reverse SSH tunnel somehow I guess?

**Comment by adoyle-h** [comment]
@Grimler91 Just type `sv start sshd` in my phone without ssh and tmux.
The ppid of 11294 is 11266, and the ppid of 11266 is 2396, which is `runsv` process.

bash version: GNU bash, version 5.1.12(1)-release
termux version: 0.117
termux-services version: 0.13

**Comment by Grimler91** [comment]
`/data/data/com.termux/files/usr/bin/sshd -D -f /data/data/com.termux/files/home/etc/ssh/sshd_config -e -R` seem to be spawned when I ssh into the device, so it is the process responsible for the shell.

If you run `sv down sshd; ps -ef | grep sshd` on device, without having an open ssh connection, then you won't see it.
Closing all connections when sshd is stopped could be reasonable

**Comment by adoyle-h** [comment]
Yes, you are right. I find an explanation about `sshd -R`.

>  the -R is an undocumented flag which SSHD uses to indicate to a child process that it has been re-executed in order to re-initialze randomization buffers

https://serverfault.com/a/1024676

So the solution is writing a script to close these connections. Like that,

```sh
$ cat <<EOF > /data/data/com.termux/files/usr/var/service/sshd/finish
#!/data/data/com.termux/files/usr/bin/sh
pkill sshd
EOF
$ chmod +x /data/data/com.termux/files/usr/var/service/sshd/finish
```

then `sv stop sshd` works.

@Grimler91 Thank you for your help.
