### ISSUE TITLE
All services can't be stopped or disabled

### ISSUE THREAD

**Issue by Leif-W** [termux/termux-services#26]
sv-disable did create the `down` files, but runit/runsv doesn't know anything about or care about any down files, completely ignores them, and runs all services anyways.  Services can't even be stopped or set to down.  I had to rm -rf all service dirs that I wanted to disable, and `kill -9` all runsv instances (1 per service).  `kill` didn't seem to work most of the time (usually no effect, if any effect, sometimes defunct/zombie, rarely ended process), but `kill -9` did end them clean.

I had sshd, mysqld, postgres, and cupsd dirs installed by default (by something else, not my intent), but did not want to run them, only maybe if-and-as-needed (rarely or never), otherwise leave it disabled.  I just wanted to play with cronie a bit, and explore various features, vs Termux:Boot.  But then the most basic features -- sv down/stop, sv-disable, don't even work...

**Comment by sylirre** [comment]
It works:

![Screenshot_20231008-140645](https://github.com/termux/termux-services/assets/107305601/e8273880-1bf2-47f5-8056-c008a1ebddef)

`sv-disable` only disables service startup when Termux is opened.

**Comment by Leif-W** [comment]
`ps auxwwf` shows process `runsv sshd` (and a logging child process) still running when `pidof` shows nothing.  `kill -9` kills a process the first time, running `kill -9` a second time shows the process does not exist.  So it did exist the first time, but not seen by `pidof`?  Is `ps` getting out-of-sync or otherwise incorrect or unreliable information from an underlying mechanism?  `sv down sshd` and `sv-disable sshd` seem to have no effect for me.  Even restarting the Termux app, which kills all cron jobs (right?  or is it wrong?  pid numbers seem to be different after ending all sessions, closing app, restarting app), indicating that all the unwanted services startup, ignoring the existence of the `down` empty file created by `sv down`'s `touch $SVDIR/down` file.

**Comment by sylirre** [comment]
The `runsv` service is a monitor instance that either starts or stops the actual service such as `sshd` as well as the logger. It should not be terminated during `down` request. Monitor looks files in service directory and makes decision whether to start or stop the service.

There should be one `runsv` instance per each service.

Runit works differently from more traditional init systems such as systemd or openrc.
