### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by izmyname** [termux/termux-services#27]

**Comment by sylirre** [comment]
Provide commands used to set up services.

**Comment by izmyname** [comment]
>sv-enable transmission

>sv up transmission

All return

 fail: transmission: unable to change to service directory: file does not exis

**Comment by sylirre** [comment]
Can't reproduce the issue.

What shell are you using? `termux-services` puts a file in `$PREFIX/etc/profile.d` directory. It is what actually makes stuff running when Termux is opened. If script in `profile.d` was not executed, the `termux-services` become unusable.

![Screenshot_20240112-001147_Termux](https://github.com/termux/termux-services/assets/107305601/cbb72f67-3dd0-4816-9860-8b827e411c54)

**Comment by izmyname** [comment]
Zsh. 

Also, I noticed the service-daemon doesn't appear as running process, even after I manually executed 'service-daemon start'. I tried to launch the script you mentioned, manually - and it appeared in htop and created necessary directories inside /bar/service, though the service itself didn't start.


service-daemon restart, however, returns this:

>Restarting daemon: service-daemonstart-stop-daemon: warning: failed to kill 12302: No such process
1 pids were not killed
No process in pidfile '/data/data/com.termux/files/usr/var/run/service-daemon.pid' found running; none killed.
cat: '/*/supervise/pid': No such file or directory
cat: '/*/log/supervise/pid': No such file or directory


The Id it fails to kill, changes everytime.

**Comment by sylirre** [comment]
It returns because you didn't set variables.

```
export SVDIR=$PREFIX/var/service
export LOGDIR=$PREFIX/var/log
(service-daemon start >/dev/null 2>&1 & )
```

Same variables needed by other utilities, not just service-daemon.

**Comment by izmyname** [comment]
I set them up, restarted termux and the process seem to appear, but it didn't fix the problem, unfortunately.

**Comment by sylirre** [comment]
Put these variables in `~/.zshrc` as well as service-daemon command.

**Comment by izmyname** [comment]
> Put these variables in `~/.zshrc` as well as service-daemon command.

I put them there an uninstalled, then installed transmission and it seemed to work - the service works now.

Thank you for the help!
