### ISSUE TITLE
sshd stops working overnight

### ISSUE THREAD

**Issue by sudomain** [termux/termux-services#6]
I'm unable to ssh into a device running Termux and the sshd service after it has been running overnight. Some details:
1. Device is left charging overnight with termux-wake-lock on
2. It's not a networking issue because `ssh -p8022 localhost` normally works but in the morning it results in `ssh: connect to host localhost port 8022: Connection refused`
3. `$PREFIX/var/log` exists but `$PREFIX/var/log/sv/` does not, so I can't check the `current` log file
4. stopping the service via `sv down sshd` then manually starting sshd using the `sshd` command allows the connection, so it's likely an issue with the service?
5. restarting the service via `sv down sshd` and `sv up sshd` also results in connection refused
6. restarting the service via `sv exit sshd` and `sv up sshd` allows the connection
7. `sv status sshd` reports the following before restarting the service:
`run: sshd: (pid 3537) 83017s, normally down; down: log: 0s, normally up, want up`
8. `sv status sshd` reports the following after restarting the service:
`run: sshd: (pid 1433) 111s, normally down; down: log: 1s, normally up, want up`

Hopefully this is enough information. If more is needed I'll need to wait until the next day before I can run more commands :)

**Comment by xeffyr** [comment]
Wake lock is only for keeping CPU awake and nothing more.

Final decision on will be process killed or not is done by Android OS. Applications can't control that behaviour, in order to prevent device overuse and battery drain. Android devices aren't designed to be servers.

**Comment by Grimler91** [comment]
Also note that you have to run `sv-enable sshd`, or `rm $PREFIX/var/service/sshd/down` to make it automatically restart after it stops, `normally down` indicates that it does not automatically restart. 

`sv-enable` unfortunately has to be run every time openssh is updated (I have been meaning to fix this), since $PREFIX/var/service/sshd/down is reinstalled on an update

**Comment by sudomain** [comment]
> Also note that you have to run sv-enable sshd

Interesting because I don't think I ever ran this command. `sv up sshd` always did the trick and doing `pkill sshd` always resulted in sshd starting again with a different pid, so I thought it was working fine. Maybe this was the issue

**Comment by Grimler91** [comment]
@sudomain alright, correction: `sv up` makes the service is restarted if it crashes or if it is killed, but it won't start it termux-services or termux crashes, or if the device is restarted. For that `sv-enable` is needed

**Comment by sudomain** [comment]
Good to know that `sv-enable` will start a job on device boot. Incase anyone encounters this overnight-sshd issue: my workaround is an hourly cronjob that runs `termux-wake-lock; sshd`. It seems to have been working the past few nights.

@Grimler91 I have a tangentially related question: Is there a separate repo for the `run` scripts and other files that are in `$PREFIX/var/service/servicename/` ? I can't find reference to specific services such as crond

**Comment by Grimler91** [comment]
> Good to know that sv-enable will start a job on device boot.

Correction again: it will start a job when termux is started, so I am using a termux:boot script with the content:
```sh
#!/data/data/com.termux/files/usr/bin/sh
source /data/data/com.termux/files/usr/etc/profile.d/start-services.sh
```
to make my services start when my device boots.

> Is there a separate repo for the run scripts

Not among our repositories, the scripts are defined in the build.sh (see for example: [1](https://github.com/termux/termux-packages/blob/f3d5a312aa1f8dc8b8eeada5e8de528582e1f8f2/packages/openssh/build.sh#L45), [2](https://github.com/termux/termux-packages/blob/f3d5a312aa1f8dc8b8eeada5e8de528582e1f8f2/packages/transmission/build.sh#L13), [3](https://github.com/termux/termux-packages/blob/f3d5a312aa1f8dc8b8eeada5e8de528582e1f8f2/packages/busybox/build.sh#L12)). There are however collections of scripts in various other places, for example: http://smarden.org/runit/runscripts.html and https://github.com/dozymoe/runit-init-scripts.
