### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by MyCompania** [termux/termux-services#8]
Добрый день. Планируете добавить Русскую локализацию?

**Comment by xeffyr** [comment]
Нет, не планируется.

Bionic libc имеет лишь базовую поддержку локалей и рассчитывать на что-то кроме `en_US.UTF-8` или `C.UTF-8` не приходится. Здесь можно посмотреть список локалей поддерживаемых Bionic libc https://github.com/aosp-mirror/platform_bionic/blob/master/libc/bionic/locale.cpp#L118-L124.

**Comment by MyCompania** [comment]
Ok
