### ISSUE TITLE
unable to change to service directory

### ISSUE THREAD

**Issue by ShivamJoker** [termux/termux-services#9]
When I am running
```sh
sv-enable mosquitto
```
It's giving me this error 
```
fail: mosquitto: unable to change to service directory: file does not exist
```

Can you please help ?
Thanks for this library

**Comment by Grimler91** [comment]
Hi, thanks for reporting!

The error happens because we have not added a service script for mosquitto. 

Could you please try if this script works?

```
mkdir -p $PREFIX/var/service/mosquitto/log
ln -s $PREFIX/share/termux-services/svlogger $PREFIX/var/service/mosquitto/log/run
cat <<- EOF > $PREFIX/var/service/mosquitto/run
#!/data/data/com.termux/files/usr/bin/sh
exec mosquitto 2>&1
EOF
chmod u+x $PREFIX/var/service/mosquitto/run
```

I can add it to the package if it seems to work.

**Comment by ShivamJoker** [comment]
Thanks the script is working perfectly, Now I can enable and disable the mosquitto using `sv-enable` command

**Comment by Grimler91** [comment]
Script added in https://github.com/termux/termux-packages/commit/ca2738c4b1a587278f42ce8e6b87bc88bcfcfc15

**Comment by mizzunet** [comment]
Why can't I start docker this way?
three's no `$PREFIX/var/service/docker` file

**Comment by Grimler91** [comment]
> Why can't I start docker this way? three's no `$PREFIX/var/service/docker` file I have this error `fail: docker: unable to change to service directory: file does not exist`

Because no one has written a service script for docker. Feel free to share yours if you come up with one that works

**Comment by mizzunet** [comment]
>> no one has written a service script 

I see

**Comment by shivaprasa1** [comment]
Instagram Brute Force 1
        [+] tor [+]
fail: start: unable to change to service directory: file does not exist

**Comment by rahaaatul** [comment]
@Grimler91 can you add a script for crond too?
